import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Hunting Coder</title>
        <meta name="description" content="Generated by create next app" />
        <meta
          name="keyword"
          content="next js,hunt code ,blog ,blog hunting coder"
        />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.container}>
        {/* <Script src='/sc.js'></Script> */}

        <main className={styles.main}>
          <div className={styles.title}>
            <h1>Hunting Coder</h1>
          </div>
          <div className={styles.description}>
            <p>A Blog For Hunting Coder by Hunting code</p>
          </div>
          <div className={styles.blogs}>
            <h2>Popular Blog</h2>
            <div className={styles.blogItem}>
              <h3>How to learn Javascript in 2023?</h3>
              <p>Javascript is the Language use Design logic for Web </p>
            </div>
            <div className={styles.blogItem}>
              <h3>How to learn Javascript in 2023?</h3>
              <p>Javascript is the Language use Design logic for Web </p>
            </div>
            <div className={styles.blogItem}>
              <h3>How to learn Javascript in 2023?</h3>
              <p>Javascript is the Language use Design logic for Web </p>
            </div>
          </div>
        </main>
      </div>
    </>
  )
}
